### ISSUE TITLE
Date timezone

### ISSUE THREAD

**Issue by ypereirareis** [jolicode/docker-images#10]
When executing: 

`docker run -t -i -v `pwd`:/project jolicode/phaudit pdepend --summary-xml=sum.xml src/`

Having this error:

`PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.`

**Comment by joelwurtz** [comment]
Thanks for the report,

Fixed in https://github.com/jolicode/docker-images/commit/2e07334f4910f0ae7db320221082434bf6a5a8ed new image will be ready in the next hour, don't forget to run 

```
docker pull jolicode/phaudit
```

to have last image
