### ISSUE TITLE
[phaudit] phpmetrics needs graphviz for the chart export option

### ISSUE THREAD

**Issue by pborreli** [jolicode/docker-images#13]
Wanted to add it myself, but not sure you want it inside phaudit Dockerfile or elsewhere
```
--chart-bubbles=CHART-BUBBLES          Path to save Bubbles chart, in SVG format. Example: /tmp/chart.svg. Graphviz **IS** required

**Comment by pborreli** [comment]
![waiting](https://cloud.githubusercontent.com/assets/77759/12244875/94531ff2-b89d-11e5-941a-703d653a46da.gif)

**Comment by joelwurtz** [comment]
![:)](https://media.giphy.com/media/sIIhZliB2McAo/giphy.gif)

**Comment by joelwurtz** [comment]
Hm, i think you can add it inside unless size of dependancies is too important but it should be ok.

**Comment by pborreli** [comment]
I guess you mean dependencies, right ? :dancer: :dancers:

**Comment by joelwurtz** [comment]
I don't know what you are talking about :-°

**Comment by ternel** [comment]
There's no space before a question mark in english. :)
-right ?
+right?

:ice_cream: :cake:

**Comment by pborreli** [comment]
I don't know what you are talking about :-°

**Comment by pborreli** [comment]
btw go push the green button [here](https://github.com/jolicode/docker-images/pull/14)
