### ISSUE TITLE
Creating archive disabled by the php.ini setting phar.readonly

### ISSUE THREAD

**Issue by jmolivas** [jolicode/docker-images#7]
I am currently testing JoliCI for [Drupal Console](http://drupalconsole.com/) project and the default container php.ini setting for creating archive `.phar` files is disabled and I am getting the following error message:

```
[UnexpectedValueException]
creating archive "/home/project/console.phar" disabled by the php.ini setting
phar.readonly
```

This is the Drupal Console project travis file 
https://github.com/hechoendrupal/DrupalAppConsole/blob/master/.travis.yml#L22

There is any plan to change the container php.ini configuration to 
```
phar.readonly = false
```

> NOTE: This is a duplicated issue from https://github.com/jolicode/JoliCi/issues/49

**Comment by joelwurtz** [comment]
Thanks,

This should be good in some minutes, (need to wait for build on docker hub registry).

I'm not a huge fan of overriding default configure here, there will be probably be a rollback of this change, and find a solution to override config in jolici instead.

**Comment by jmolivas** [comment]
There is a command I need to run to get the new container configuration ?

**Comment by joelwurtz** [comment]
Yes you need to pull or remove image manually to get the new version, jolici does not check new image version by itself (something that will be added later)

```
docker pull jolicode/php53
docker pull jolicode/php54
...
```

**Comment by jmolivas** [comment]
Thanks that work great.
